server:
  port: 5078
  servlet:
    context-path: /gpstracker/api/

spring:
  application:
    name: gps-tracker

  datasource:
    url: jdbc:postgresql://localhost:5432/gps
    username: postgres
    password: Password@123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

jwt:
  secret: mySecretKey123456789012345678901234567890
  expiration: 86400000
